version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: sk-proj-Qh6023n5FPk6ZL0wuW8dd3BlbkFJ533ylvu1uYBlUNYdrgPi
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
